packages:
  - "frontend"
  - "backend"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

verifyDepsBeforeRun: false

onlyBuiltDependencies:
  - msgpackr-extract

overrides:
  standardwebhooks: ^1.1.1

minimumReleaseAgeExclude:
  - standardwebhooks@1.1.1
